spring.application.name=backend
spring.datasource.url=postgresql://postgres:[nIaFguEmXX1kUuqL]@db.jkdahlkcgjyiqnodvbix.supabase.co:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=nIaFguEmXX1kUuqL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081